// ACTIONS FOR AUTHENTICATION/AUTHORIZATION
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const UPDATE_INFO_USERS = "UPDATE_INFO_USERS";
export const LOGOUT = "LOGOUT";
export const CLEAR = "CLEAR";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_USER = "GET_USER";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const SEND_LINK_RESET = "SEND_LINK_RESET";
export const SEND_LINK_ERROR = "SET_LINK_ERROR";
export const GET_LINK_RESET = "GET_LINK_RESET";
export const GET_LINK_ERROR = "GET_LINK_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

// ACTIONS FOR PRODUCTS
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";


